### ISSUE TITLE
Which parts of SQL are simplified by IR?

### ISSUE THREAD

**Issue by guotong1988** [microsoft/IRNet#9]
https://github.com/microsoft/IRNet/issues/7

We know that: As IR simplify the logic form, so IR improve the experiment results.

Then what parts of SQL are simplified by IR?

**Comment by substill** [comment]
Although SQL is a declarative language, it still contains clauses that are directly related to the data storage schema, e.g., JOIN, From. These clauses are designed for implementation purpose rather than meaning representation, they do not have their corresponding surfaces in users NL questions. Given a well defined database schema, e.g., Star Schema, these part can be derived.

**Comment by guotong1988** [comment]
Thank you.
